### PR TITLE
Product Page Components: Fix dist issues

### PR DESCRIPTION
**Pull request by zdmitchell**
This pull does several things:
- Builds typescript files, which we were forgetting to do before
- Converts the flags svgs to be React components
- Exports the `StoreFlag` component

Inkofpixel needs to use this repo while they're developing the footer, and they discovered some issues while trying to use it from npm.

Connects https://github.com/iFixit/ifixit/issues/35956

### CODE REVIEW

**Comment by sterlinghirsh** [comment]
CR :zap:

**Comment by GrantMatejka** [comment]
CR :corn:

**Comment by ardelato** [comment]
@zdmitchell do you have any suggestions on how to QA this or what issues InkofPixel are running into? 

My idea is to double check the flag components on the Demo page and also create a new test page where I try to import some components for usage.

**Comment by zdmitchell** [comment]
> My idea is to double check the flag components on the Demo page and also create a new test page where I try to import some components for usage.

That sounds like a good idea to me.

**Comment by ardelato** [comment]
> > My idea is to double check the flag components on the Demo page and also create a new test page where I try to import some components for usage.
> 
> That sounds like a good idea to me.

Rodger that 👍  

Do you happen to have information on what issues InkofPixel are running into? @zdmitchell

**Comment by zdmitchell** [comment]
> Do you happen to have information on what issues InkofPixel are running into?

@ardelato They mentioned it somewhat in https://ifixit.slack.com/archives/C01K32B4FPX/p1611858325013200. Basically, the three things this pull fixes:
1. They didn't have access to components that were built using TypeScript.
2. They needed to add an SVG loader to get the components to compile, when really everything should have worked out of the box.
3. They wanted access to the `StoreFlag` component.

**Comment by ardelato** [comment]
This was a dozy to QA, but QA 💯  nonetheless.

| Master Branch npm package import	| This Branch npm pack import	|
|:---:|:---:|
|Master failed component	|New Branch components	|

## Steps Taken:
1. Git cloned this repo on my local machine (not Cominor)
2. Ran `npm install` while the master branch was checked out
3. Ran `npm run build`
4. Ran `npm pack` to properly bundle up the directory based off the build folder(https://medium.com/@vcarl/problems-with-npm-link-and-an-alternative-4dbdd3e66811) 
5. Created a new react app in the parent directory of where I git cloned this repo
    5a. `npx create-react-app pcc-test-mater` 
6. I then copied over the `.tgz` file which was created from `npm pack` into this new react app. As well as copied over the `stores.json` and `languages.json` files. 
7. In the new react app, `pcc-test-master`, I ran `npm install filename.tgz` to install `@ifixit/product-page-components` afterwards. I did not have to run `npm install` since creating a new react app automatically installs basic node modules.
8. I ran `npm start` to ensure the default react page still rendered without issues ✅ 
9. I modified the `App.js` file in `src/` to import the `StoreDropdown` and `LanguageDropdown` components from `@ifixit/product-page-components` as the json files
```diff
+import {StoreDropdown,LanguageDropdown} from '@ifixit/product-page-components';
+import stores from './stores.json';
+import languages from './languages.json';
+
 function App() {
   return (
     <div className="App">
       <header className="App-header">
+        <StoreDropdown stores={stores} onClickStore={store => console.log(store)} />
+         <hr />
+         <LanguageDropdown
+            languages={languages}
+            translationPreferencesUrl="https://www.cominor.com/Login"
+            machineTranslationEnabled
+            isLightTheme
+            machineTranslationRequested={false}
+         />
         <img src={logo} className="App-logo" alt="logo" />
         <p>
           Edit <code>src/App.js</code> and save to reload.
```
10. I modified `src/App.css` and completed removed everything in `src/index.css`
```diff
 .App-header {
-  background-color: #282c34;
+
   min-height: 100vh;
   display: flex;
   flex-direction: column;
   align-items: center;
   justify-content: center;
-  font-size: calc(10px + 2vmin);
-  color: white;
-}
 
-.App-link {
-  color: #61dafb;
 }
```
11. I ran `npm start` again and got a `Failed to Compile` error page that talks about importing the SVG flags. Which I assumed is the same error InkOfPixel got.

12. I repeated steps 1-11 this time with the this branch checked out for `step 2`.
13. The page was successful in rendering and I continued to test the components worked as expected similar to #31 
    13a. Though, I ran `window.onbeforeunload = function(){ return 'Leave page?'; };` in the console for the react app to stop redirecting when I clicked on the language links.

**Pull request merged**
