### PR TITLE
Product Review Name: Reduce size

### PR DESCRIPTION
**Pull request by cdcline**
It was too large, this reduces it to a smaller size.

The mockup image was:
image

18px is
image
16px is
image
15px is
image

### CODE REVIEW

**Comment by sctice** [comment]
CR :flags:

**Comment by sterlinghirsh** [comment]
CR :zap:

**Comment by ardelato** [comment]
QA 👍 

| Master Branch	| This Branch	|
|:---:|:---:|
|Master Branch Text Size_CleanShot	| Text Resize New Branch_CleanShot	|

Also confirmed no issues using the Product Review component when installing as a package. 

## Steps Taken:
1. Followed the steps from this guide https://overlord.dozuki.com/Wiki/QA_Testing_the_Repo_%22product-page-components%22 
2. Conducted the smoke tests from the guide as well.

**Comment by ardelato** [comment]
Is this good to go out @cdcline?

**Pull request merged**
