### PR TITLE
Reviews: Truncate body on frontend

### PR DESCRIPTION
**Pull request by mlahargou**
We want to stop passing the truncated body through the api. It is
unnecessary because we can just truncate on the frontend.

This will have to be merged before the ifixit side pull gets merged.

QA:
--
Mess around with the data inside of `src/example/example_reviews.json`. 
You can run `npm start` to bring up the example page and make sure things 
behave properly.

CC @batbattur @ardelato 

Connects https://github.com/iFixit/ifixit/issues/31382

### CODE REVIEW

**Comment by batbattur** [comment]
Checked using long strings:
- Truncates to 300 characters, if the body is longer than 300 chars, when not expanded. ✅ 
- When expanded, displays all of the review body. ✅ 
- No js errors in the browser console. ✅ 

https://user-images.githubusercontent.com/58952979/126715130-aefeb9ff-9b53-410b-a1f2-ef820da922a3.mov

QA 👍

**Comment by cdcline** [comment]
CR 👍

**Comment by GrantMatejka** [comment]
CR :corn:

**Comment by mlahargou** [comment]
Sorry, needed to make a new version. CR :carry-over: QA :carry-over:

**Comment by GrantMatejka** [comment]
CR :carry-over-me-too:

**Pull request merged**
