### PR TITLE
Setup GH Action to run tests

### PR DESCRIPTION
**Pull request by evannoronha**
Summary
---
This pull adds a CI config to the repo so that GH Actions will build a docker image and run tests against the image on pull requests and new commits to master.

I also updated a test since the snapshots were out of date.

qa_req 0

Closes: https://github.com/iFixit/ifixit/issues/33387

### CODE REVIEW

**Comment by evannoronha** [comment]
dev_block 🔥

**Comment by zdmitchell** [comment]
CR :guitar:

**Comment by zdmitchell** [comment]
CR :guitar:

**Comment by evannoronha** [comment]
un_dev_block 🔥

**Comment by danielbeardsley** [comment]
CR 👍 

> found 20102 vulnerabilities (20095 low, 7 high)

Oh npm...

So that we're aware, the "build" took 2minutes (docker + npm install) and the tests took 4s.

image

**Comment by evannoronha** [comment]
> So that we're aware, the "build" took 2minutes (docker + npm install) and the tests took 4s.

When running the scripts by hand it becomes clear that the bulk of that time is in `npm install`. I'm not sure how to speed that up since we can't rely any caching benefits on the ephemeral instance. But, since this is on a public repo and has unlimited CPU time, it's just inconvenient for now.

**Comment by danielbeardsley** [comment]
> I'm not sure how to speed that up since we can't rely any caching benefits on the ephemeral instance

They've thought of everything!

https://docs.github.com/en/free-pro-team@latest/actions/guides/caching-dependencies-to-speed-up-workflows

**Pull request merged**
